version: "3"

services:
  hadoop:
    image:  ghcr.io/kasipavankumar/hadoop-docker:1.0.3
    container_name: hadoop
    restart: always
    ports:
      - 9870:9870
      - 9010:9000
    volumes:
      - hadoop:/hadoop/dfs/hadoop
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: mysql
  
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5430:5430'
    volumes: 
      - db:/var/lib/postgresql/data
    container_name: postgres
  
  sqoop:
    image: nebasam/sqoop:1
    container_name: sqoop
    depends_on:
      - hadoop
volumes:
  hadoop:
  db:
    driver: local
